create table if not exists public.spins (
  id bigint generated by default as identity primary key,
  mobile text not null unique check (mobile ~ '^[6-9][0-9]{9}$'),
  prize_index smallint not null check (prize_index between 0 and 7),
  prize_title text not null,
  prize_code text not null,
  claimed_at timestamptz not null default now()
);

alter table public.spins enable row level security;

-- Contest entries are private. The browser cannot list or modify them.
-- The Edge Function uses the server-only service role to create a result.
revoke all on table public.spins from anon, authenticated;
revoke all on sequence public.spins_id_seq from anon, authenticated;

create index if not exists spins_claimed_at_idx on public.spins (claimed_at desc);

comment on table public.spins is
  'Selvam Sarees contest winners. Viewable only from the Supabase dashboard.';
